version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: amelini
      MYSQL_PASSWORD: Casaanto1
      MYSQL_DATABASE: sistema_stock


